version: "3.4"
networks:
  app:
services:
  db:
    container_name: db
    image: mongo:4.2.6
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - app
    volumes:
      - ./dbdata:/data/db
  server:
    container_name: server
    build:
      context: ./packages/server
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - app
    volumes:
      - ./packages/server:/app
      - /app/node_modules
    depends_on:
      - db